workflows:
  ios-appstore:
    name: iOS App Store Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - TaskIQ_AppStore_Profile
        certificates:
          - Apple Distribution: Vishal Dadia (35N48PFMJY)

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build signed IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa