workflows:
  ios-appstore:
    name: iOS App Store Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.taskiq.taskiq.ios
        certificate_reference: TASKIQ_DIST_CERT
        provisioning_profile_reference: TaskIQ_AppStore_Profile

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build signed IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa