// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvd6Zb7cbn7XIfdYlwYsDPh4wERPNISyk',
    appId: '1:843862557345:web:5c404170d56991a1eae6e0',
    messagingSenderId: '843862557345',
    projectId: 'taskiq-ad680',
    authDomain: 'taskiq-ad680.firebaseapp.com',
    storageBucket: 'taskiq-ad680.firebasestorage.app',
    measurementId: 'G-LP3YKQ8HBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9DGtKkf4OONnTFKghkTbTSn5gCVxt_Os',
    appId: '1:843862557345:android:08bcd6112323319feae6e0',
    messagingSenderId: '843862557345',
    projectId: 'taskiq-ad680',
    storageBucket: 'taskiq-ad680.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX324ZRe9HzFmnwahfz6XdPDtVS_BVnSw',
    appId: '1:843862557345:ios:fe9db2e9a193a27beae6e0',
    messagingSenderId: '843862557345',
    projectId: 'taskiq-ad680',
    storageBucket: 'taskiq-ad680.firebasestorage.app',
    androidClientId: '843862557345-jb5hthctfekl35m8d1qujd9ocs5tfeov.apps.googleusercontent.com',
    iosClientId: '843862557345-shic64io5nbe4b32n1p5qev72s8m52dd.apps.googleusercontent.com',
    iosBundleId: 'com.taskiq.taskiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvd6Zb7cbn7XIfdYlwYsDPh4wERPNISyk',
    appId: '1:843862557345:web:a82c0663953fe6f8eae6e0',
    messagingSenderId: '843862557345',
    projectId: 'taskiq-ad680',
    authDomain: 'taskiq-ad680.firebaseapp.com',
    storageBucket: 'taskiq-ad680.firebasestorage.app',
    measurementId: 'G-6D9R9767NB',
  );
}
